# PistonJump Configuration file
# @author syam <admin@sakura-server.net>
# BukkitDev: http://dev.bukkit.org/server-mods/pistonjump/

#==================#
#   Basic Config   #
#==================#
Player:
# Ignore Permissions (pistonjump.jump: true)
  IgnorePermission: false
# Enable sideways Pistons
  EnableSidewaysPiston: true
# If it is false, ignore power sign under the piston.
# (Max power is 8.0)
  CheckSign: true
# Default player injection power. If set to 0, must use the sign to jump.
  DefaultPower: 3.0

Block:
  Enable: true
  EnableSidewaysPiston: true
  CheckSign: true
  DefaultPower: 0.0

#==================#
#   DO NOT TOUCH   #
#==================#
# Do not touch this option! It is a check if you are running the recent configuration version
version: 0.5